module.exports =
    physics:              'Physics'
    biology:              'Biology'
    macro_economics:      'Macro Economics'
    college_physics:      'College Physics'
    micro_economics:      'Micro Economics'
    concepts_biology:     'Concepts of Biology'
    intro_sociology:      'Intro to Sociology'
    anatomy_physiology:   'Anatomy and Physiology'
    principles_economics: 'Principles of Economics'
