# `sudo:false` for faster builds.
sudo: false
language: node_js
git:
  lfs_skip_smudge: true
env:
  - TEST=integration
  - OX_PROJECT=tutor
  - OX_PROJECT=exercises
  - OX_PROJECT=shared

# addons:
#   apt:
#     packages:
#       - shellcheck
#       # For building kcov
#       - libcurl4-openssl-dev
#       - libelf-dev
#       - libdw-dev
#       - cmake

# Cache the 3rd-party packages. From https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache:
  yarn: true
  directories:
    - ~/.cache
script: ./script/ci
after_failure:
  - npm list
after_success:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
  # Report to coveralls
  - cat ./coverage/*/lcov.info | node ./node_modules/.bin/coveralls --verbose
