version: '3.5'
services:
  build:
    command: bash -c "if [ -z \"`ls -A node_modules`\" ]; then yarn; fi && yarn serve exercises"
    build:
      context: .
      target: builder
    working_dir: /code
    environment:
      - "OX_PROJECT_HOST=0.0.0.0"
    volumes:
      - .:/code:cached
    ports:
      - "8001:8001"
