ROUTES = [{
  subject: 'task'
  method: 'GET'
  pattern: 'tasks/{id}'
}, {
  subject: 'task'
  method: 'DELETE'
  pattern: 'tasks/{id}'
}, {
  subject: 'task-plan'
  method: 'GET'
  pattern: 'plans/{id}'
}, {
  subject: 'task-plan'
  method: 'DELETE'
  pattern: 'plans/{id}'
}, {
  subject: 'task-plan'
  method: 'POST'
  pattern: 'courses/{courseId}/plans'
}, {
  subject: 'task-plan'
  method: 'PATCH'
  pattern: 'plans/{id}'
}, {
  subject: 'task-plan-review'
  method: 'GET'
  pattern: 'plans/{id}/review'
}, {
  subject: 'task-plan-stats'
  method: 'GET'
  pattern: 'plans/{id}/stats'
}, {
  subject: 'ecosystem-exercises'
  method: 'GET'
  # send page ids as params
  pattern: 'ecosystems/{id}/exercises/{requestType}'
}, {
  subject: 'course-exercises'
  method: 'GET'
  pattern: 'courses/{id}/exercises/{requestType}'
}, {
  subject: 'course-exercises'
  action: 'exclude'
  method: 'PUT'
  pattern: 'courses/{id}/exercises'
}, {
  subject: 'ecosystem-readings'
  method: 'GET'
  pattern: 'ecosystems/{id}/readings'
}, {
  subject: 'course-guide'
  method: 'GET'
  pattern: 'courses/{id}/guide'
}, {
  subject: 'course'
  method: 'GET'
  pattern: 'courses/{id}'
}, {
  subject: 'course'
  method: 'PATCH'
  pattern: 'courses/{id}'
}, {
  subject: 'course-dashboard-teacher-cc'
  method: 'GET'
  pattern: 'courses/{id}/cc/dashboard'
}, {
  subject: 'course-practice'
  method: 'GET'
  pattern: 'courses/{id}/practice'
}, {
  subject: 'course-practice'
  method: 'POST'
  pattern: 'courses/{id}/practice'
}, {
  subject: 'course-performance-forecast-student'
  method: 'GET'
  pattern: 'courses/{id}/guide'
}, {
  subject: 'course-performance-forecast-teacher'
  method: 'GET'
  pattern: 'courses/{id}/teacher_guide'
}, {
  subject: 'course-performance-forecast-teacher-as-student'
  method: 'GET'
  pattern: 'courses/{id}/guide/role/{roleId}'
}, {
  subject: 'course-scores'
  method: 'GET'
  pattern: 'courses/{id}/performance'
}, {
  subject: 'course-scores-export'
  method: 'GET'
  pattern: 'courses/{id}/performance/exports'
}, {
  subject: 'course-scores-export'
  method: 'POST'
  pattern: 'courses/{id}/performance/export'
}, {
  subject: 'task-scores'
  method: 'PUT'
  action: 'accept-late-work'
  pattern: 'tasks/{id}/accept_late_work'
}, {
  subject: 'task-scores'
  method: 'PUT'
  action: 'reject-late-work'
  pattern: 'tasks/{id}/reject_late_work'
}, {
  subject: 'course-dashboard-teacher'
  method: 'GET'
  pattern: 'courses/{id}/dashboard'
}, {
  subject: 'job'
  method: 'GET'
  pattern: 'job/{id}'
  handledErrors: ['*']
}, {
  subject: 'ecosystem'
  method: 'GET'
  pattern: 'ecosystems'
}, {
  subject: 'teacher'
  method: 'DELETE'
  pattern: 'teachers/{id}'
}, {
  subject: 'student'
  method: 'DELETE'
  pattern: 'students/{id}'
}, {
  subject: 'student'
  method: 'PATCH'
  pattern: 'students/{id}'
}, {
  subject: 'student'
  method: 'PATCH'
  pattern: 'students/{id}'
  action: 'save-student-identifier'
  # handledErrors: ['student_identifier_has_already_been_taken']
}, {
  subject: 'student'
  method: 'PUT'
  action: 'undrop'
  pattern: 'students/{id}/undrop'
  # handledErrors: ['already_active', 'student_identifier_has_already_been_taken']
}, {
  subject: 'course-roster'
  method: 'GET'
  pattern: 'courses/{id}/roster'
}, {
  subject: 'course-roster'
  method: 'POST'
  pattern: 'courses/{id}/roster'
}, {
  subject: 'course-student-id'
  method: 'PATCH'
  pattern: 'user/courses/{id}/student'
  handledErrors: ['*']
}, {
  subject: 'period'
  method: 'POST'
  pattern: 'courses/{courseId}/periods'
}, {
  subject: 'period'
  method: 'PATCH'
  pattern: 'periods/{id}'
}, {
  subject: 'period'
  method: 'DELETE'
  pattern: 'periods/{id}'
}, {
  subject: 'period'
  method: 'PUT'
  action: 'restore'
  pattern: 'periods/{id}/restore'
}, {
  subject: 'step'
  method: 'GET'
  pattern: 'steps/{id}'
}, {
  subject: 'step'
  method: 'GET'
  action: 'personalize'
  pattern: 'steps/{id}'
  handledErrors: ['*']
}, {
  subject: 'step'
  method: 'PUT'
  action: 'complete'
  pattern: 'steps/{id}/completed'
}, {
  subject: 'step'
  method: 'PUT'
  action: 'recover'
  pattern: 'steps/{id}/recovery'
}, {
  subject: 'step'
  method: 'PATCH'
  action: 'answer'
  pattern: 'steps/{id}'
}, {
  subject: 'user'
  method: 'GET'
  pattern: 'user'
}, {
  subject: 'user-courses'
  method: 'GET'
  pattern: 'user/courses'
}, {
  subject: 'course-clone'
  method: 'POST'
  pattern: 'courses/{id}/clone'
}, {
  subject: 'course'
  method: 'POST'
  pattern: 'courses'
}, {
  subject: 'book-page'
  method: 'GET'
  pattern: 'pages/{id}'
}, {
  subject: 'book-page'
  method: 'GET'
  action: 'read-silent'
  pattern: 'pages/{id}'
  handledErrors: ['*']
}, {
  subject: 'book-exercise'
  method: 'GET'
  pattern: '{url}'
}, {
  subject: 'course-dashboard-student'
  method: 'GET'
  pattern: 'courses/{id}/dashboard'
}, {
  subject: 'notification'
  method: 'GET'
  pattern: 'notifications'
  handledErrors: ['*']
}]

module.exports = ROUTES
