routes = [{
    subject: 'exericise'
    action: 'save'
    method: 'PATCH'
    pattern: 'api/steps/{id}'
  }, {
    subject: 'exericise'
    action: 'complete'
    method: 'PUT'
    pattern: 'api/steps/{id}/completed'
  }, {
    subject: 'exericise'
    action: 'fetch'
    method: 'GET'
    pattern: 'api/steps/{id}'
  }, {
    subject: 'task'
    action: 'fetch'
    method: 'GET'
    pattern: 'api/tasks/{id}'
  }, {
    subject: 'task'
    action: 'fetchByModule'
    method: 'GET'
    pattern: 'api/cc/tasks/{collectionUUID}/{moduleUUID}'
  }, {
    subject: 'user'
    topic: 'status'
    action: 'fetch'
    method: 'GET'
    pattern: 'auth/status'
    withCredentials: true
  }, {
    subject: 'courseDashboard'
    action: 'fetch'
    method: 'GET'
    pattern: 'api/courses/{id}/cc/dashboard'
  }, {
    subject: 'course'
    action: 'prevalidation'
    method: 'POST'
    pattern: 'api/enrollment_changes/prevalidate'
  }, {
    subject: 'course'
    action: 'registration'
    method: 'POST'
    pattern: 'api/enrollment_changes'
  }, {
    subject: 'course'
    action: 'confirmation'
    method: 'PUT'
    pattern: 'api/enrollment_changes/{id}/approve'
  }, {
    subject: 'course'
    action: 'studentUpdate'
    method: 'PATCH'
    pattern: 'api/user/courses/{id}/student'
}]

module.exports = routes
