#!/bin/bash

export NODE_OPTIONS=–max_old_space_size=4096

cd "$(dirname "$0")/.." || exit 111

TEST=$1

if [[ "$TEST" = "lint" ]]; then
  ./bin/lint || exit 112
elif [[ "$TEST" = "e2e" ]]; then
  yarn run tutor:test:server && ./bin/test $TEST --all
else
  ./bin/test $TEST --all
fi
