#!/bin/bash

cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

if [[ "$TEST" = "integration" ]]; then
  yarn run tutor:test:server &
  yarn run tutor:test:cypress
else
  ./bin/lint || exit 112
  ./bin/test $OX_PROJECT --all
fi
