#!/bin/sh

if [ $# -eq 0 ]; then
    echo "No destination for screen was given. usage:"
    echo "$0 <path to tutor server>"
    exit 1
fi

DEST=$1/app/views/webview/index.html.erb

$(npm bin)/babel-node ./tutor/static-loading-screen.js > $DEST

echo Wrote loading screen to $DEST
