#!/bin/bash

PROJECT=${OX_PROJECT:=tutor}

if [ "$TRAVIS" == "true" ]; then
    echo "running under travis, fetching master"
    # fetch master so it can be compared
    git remote set-branches --add origin master
    git fetch
fi

if [ "$1" == "branch" ]; then
    cmd="git diff-tree -r --diff-filter=ACMR --no-commit-id --name-only origin/master head ${PROJECT}/src ${PROJECT}/specs"
    echo $cmd
    echo `${cmd}`
    ${cmd} | grep -v __snapshots__ | xargs $(npm bin)/eslint $2
else
    git status --short --porcelain ${PROJECT}/src ${PROJECT}/specs | awk '{ print $2 }' | xargs $(npm bin)/eslint
fi
