#!/usr/bin/env bash
set -e; if [ -n "$DEBUG" ]; then set -x; fi

yarn serve tutor &

tutor_server_dir="/tmp/tutor-server"

if [ ! -d "$tutor_server_dir/.git" ]; then
  rm -rf "$tutor_server_dir"
  git clone git@github.com:openstax/tutor-server.git "$tutor_server_dir"
fi

cd "$tutor_server_dir"

git checkout heroku-support

bundle install

bin/rake db:setup
bin/rake db:demo
bin/rails s -p 80
