#!/bin/bash

set -e
if [ $# -eq 0 ]; then
    echo "No project to build was given. usage:"
    echo "$0 <tutor|exercises|coach>"
    exit 1
fi

export OX_PROJECT=$1
echo Building: $OX_PROJECT
export NODE_ENV=production

webpack --progress --config webpack.config.js

if [ $2 == "archive" ]; then
   # credit/blame to: http://stackoverflow.com/questions/8201729/rename-files-to-md5-sum-extension-bash
   for F in dist/*.min.*; do
       mv $F `md5sum $F | perl -MFile::Basename -ne '($m, $f) = split(/\s+/,$_); $f=basename($f); $f =~ m/(.*?)\.(.*)/; print "dist/$1-$m.$2"'`
   done
   tar -czf archive.tar.gz dist/*
fi
