require './components/breadcrumb/index.spec'
require './components/buttons/async-button.spec'
require './components/buttons/close-button.spec'
require './components/buttons/refresh-button.spec'
# require './components/change-student-id-form.spec'
# require './components/chapter-section-mixin.spec'
require './components/exercise/free-response.spec'
# require './components/exercise/group.spec'
# require './components/exercise/index.spec'
# require './components/exercise-badges/index.spec'
# require './components/exercise-identifier-link.spec'
# require './components/exercise-preview/index.spec'
require './components/html.spec'
# require './components/notifications/email.spec'
require './components/notifications/pollers.spec'
# require './components/notifications/system.spec'
# require './components/pinned-header-footer-card/index.spec'
# require './components/question/answer.spec'
# require './components/question/index.spec'
# require './components/smart-overflow.spec'
require './components/spy-mode.spec'
require './components/surety-guard.spec'
require './components/urls.spec'
require './helpers/mathjax.spec'
require './helpers/task.spec'
require './model/exercise.spec'
require './model/notifications.spec'
require './model/ui-settings.spec'
require './model/user.spec'

# Once all specs are passing, remove the above and re-enable this:
#
# testsContext = require.context("./", true, /\.spec\.(cjsx|coffee)$/)
# testsContext.keys().forEach(testsContext)
