name: Build

on:
  release:
    types:
      - published

jobs:
  tutor:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Build assets
        run: yarn run build tutor
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TUTOR_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TUTOR_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.TUTOR_AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.TUTOR_AWS_S3_BUCKET }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          SOURCE_DIR: tutor/dist
