name: Build

on:
  release:
    types:
      - published

jobs:
  tutor:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v2

      - name: Install npm
        uses: bahmutov/npm-install@v1

      - name: Build tutor-js assets
        run: yarn run build tutor
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}

  exercises:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v2

      - name: Install npm
        uses: bahmutov/npm-install@v1

      - name: Build exercises-js assets
        run: yarn run build exercises
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
