name: TutorJS

on:
  push:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: openstax/tutor-server@mini_book_docker
      - name: Run tests
        run: yarn run ci e2e
      - name: Save screenshots of failures
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: failure-screenshots
          path: screenshots/tutor
