name: Tutor End 2 End Tests

on:
  push:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: actions/checkout@v2
        with:
          repository: openstax/tutor-server
          ref: main
          path: tutor-server
      - uses: ./tutor-server/
      - name: Run tests
        run: yarn run ci e2e
      - name: Save screenshots of failures
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: failure-screenshots
          path: screenshots/tutor
