name: TutorJS

on:
  push:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        project: ['lint', 'tutor', 'shared', 'exercises', 'integration']
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn run ci ${{ matrix.project }}
